Environment:
 cluster: Minerva
 server: 
project_directory: /scratch/username/RNAseq_projects/
Short-read_aligners:
 tophat2: tophat/2.0.9
 bowtie2: bowtie2/2.1.0
 STAR: rna-star/2.3.0e
genomes: 
 mouse: 
  rRNApath: 
  tophat2:  
   gtf: /scratch/username/genomes/Mus_musculus/Ensembl/NCBIM37/Annotation/Genes/genes.gtf
   index: /scratch/username/genomes/Mus_musculus/Ensembl/NCBIM37/Sequence/Bowtie2Index
  exonicPath: 
  intronicPath:
  intragenicPath:
  intergenicPath:
  STAR:
    path: /scratch/username/mm9_star

