Environment:
 cluster: Minerva
 server: 
project_directory: /home/immanuel/Documents/test_project_pipeline/
Short-read_aligners:
 tophat2: tohpat2
 bowtie2: bowtie2
 STAR: STAR
genomes:
 mouse: 
  rRNApath:
  tophat2:   
   gtf: /home/immanuel/Documents/test_genome/test_genes.gtf
   index: /home/immanuel/Documents/test_genome/bowtie2Index_test/
  exonicPath: /test/
  intronicPath:
  intragenicPath:
  intergenicPath:
  STAR:
    path:

